I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 278, in script
    python:
ScriptError: could not find label 'Alleenwerk'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Remco\renpy-8.0.0-sdk\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "C:\Users\Remco\renpy-8.0.0-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "C:\Users\Remco\renpy-8.0.0-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "C:\Users\Remco\renpy-8.0.0-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "C:\Users\Remco\renpy-8.0.0-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'Alleenwerk'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
Life of Meta 1.0
Fri Aug 19 12:07:45 2022
